name = "Dalli AI"
uid = "52c31498-a2e9-11eb-bcbc-0242ac130002"
version = 3
copyright = "Softles"
description = "When you first saw Dalli, were you blinded by its majesty?"
author = "Softles"
url = "https://github.com/HardlySoftly/Dalli-AI"
icon = "/mods/DalliAI/bugfix.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
