BuilderGroup {
    BuilderGroupName = 'DalliT1Platoons',
    BuildersType = 'PlatoonFormBuilder',
    Builder {
        BuilderName = 'DalliT1AirScout',
        PlatoonTemplate = 'T1AirScoutForm',
        Priority = 400,
        InstanceCount = 200,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseFormation = 'AttackFormation',
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliT1LandScout',
        PlatoonTemplate = 'T1LandScoutForm',
        Priority = 400,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseFormation = 'AttackFormation',
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliT1Raiding',
        PlatoonTemplate = 'DalliT1Raid',
        Priority = 300,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseMoveOrder = false,
            PrioritizedCategories = {
                'ENGINEER TECH1',
            },
        },        
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliT1Hunting',
        PlatoonTemplate = 'DalliT1Hunt',
        Priority = 200,
        InstanceCount = 1,
        BuilderType = 'Any',
        BuilderData = { },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliT1Attack1',
        PlatoonTemplate = 'DalliT1Attack',
        Priority = 100,
        InstanceCount = 200,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseFormation = 'AttackFormation',
            UseMoveOrder = false,
            PrioritizedCategories = {
                'MASSEXTRACTION',
                'ENERGYPRODUCTION',
                'FACTORY',
            },
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliT1Attack2',
        PlatoonTemplate = 'DalliT1Attack',
        Priority = 100,
        InstanceCount = 200,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseFormation = 'AttackFormation',
            UseMoveOrder = true,
            PrioritizedCategories = {
                'MOBILE LAND',
                'MOBILE ENGINEER',
            },
        },
        BuilderConditions = { },
    },
    
    Builder {
        BuilderName = 'DalliT1AirDefense',
        PlatoonTemplate = 'DalliT1AirDefense',
        Priority = 100,
        InstanceCount = 1,
        BuilderType = 'Any',
        BuilderData = { },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliT1AirRaid',
        PlatoonTemplate = 'DalliT1AirRaid',
        Priority = 200,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            PrioritizedCategories = {
                'ENGINEER TECH1',
                'ENGINEER TECH2',
                'ENGINEER TECH3',
                'MASSEXTRACTION',
            },
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliT1AirUnitBombing',
        PlatoonTemplate = 'DalliT1AirUnitBombing',
        Priority = 200,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            PrioritizedCategories = {
                'MOBILE LAND',
            },
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliT1AirAttack',
        PlatoonTemplate = 'DalliT1AirAttack',
        Priority = 100,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            PrioritizedCategories = {
                'ENERGYPRODUCTION',
                'MASSEXTRACTION',
            },
        },
        BuilderConditions = { },
    },
}
