BuilderGroup {
    BuilderGroupName = 'DalliConstPlatoons',
    BuildersType = 'PlatoonFormBuilder',
    Builder {
        BuilderName = 'DalliConstT1AirScout',
        PlatoonTemplate = 'T1AirScoutForm',
        Priority = 400,
        InstanceCount = 200,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseFormation = 'AttackFormation',
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliConstT1LandScout',
        PlatoonTemplate = 'T1LandScoutForm',
        Priority = 400,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseFormation = 'AttackFormation',
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliConstT1Raiding',
        PlatoonTemplate = 'DalliConstT1Raid',
        Priority = 300,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseMoveOrder = false,
            PrioritizedCategories = {
                'ENGINEER TECH1',
            },
        },        
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliConstT1Hunting',
        PlatoonTemplate = 'DalliConstT1Hunt',
        Priority = 200,
        InstanceCount = 1,
        BuilderType = 'Any',
        BuilderData = { },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliConstT1Attack',
        PlatoonTemplate = 'DalliConstT1Attack',
        Priority = 100,
        InstanceCount = 200,
        BuilderType = 'Any',
        BuilderData = {
            NeverGuardBases = true,
            NeverGuardEngineers = true,
            UseFormation = 'AttackFormation',
            UseMoveOrder = false,
            PrioritizedCategories = {
                'MASSEXTRACTION',
                'ENERGYPRODUCTION',
                'ENGINEER',
                'FACTORY',
                'LAND',
            },
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliConstT1AirDefense',
        PlatoonTemplate = 'DalliConstT1AirDefense',
        Priority = 100,
        InstanceCount = 1,
        BuilderType = 'Any',
        BuilderData = { },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliConstT1AirRaid',
        PlatoonTemplate = 'DalliConstT1AirRaid',
        Priority = 200,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            PrioritizedCategories = {
                'ENGINEER TECH1',
                'ENGINEER TECH2',
                'ENGINEER TECH3',
                'MASSEXTRACTION',
            },
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliConstT1AirUnitBombing',
        PlatoonTemplate = 'DalliConstT1AirUnitBombing',
        Priority = 200,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            PrioritizedCategories = {
                'MOBILE LAND',
            },
        },
        BuilderConditions = { },
    },
    Builder {
        BuilderName = 'DalliConstT1AirAttack',
        PlatoonTemplate = 'DalliConstT1AirAttack',
        Priority = 100,
        InstanceCount = 2,
        BuilderType = 'Any',
        BuilderData = {
            PrioritizedCategories = {
                'ENERGYPRODUCTION',
                'MASSEXTRACTION',
            },
        },
        BuilderConditions = { },
    },
}
